//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCard
    {
        public int BankCardID { get; set; }
        public string BankCardNumber { get; set; }
        public int BankCardOwner { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
